### ISSUE TITLE
hello giulio i have this problem with ops3 when y try to run ops3_deorbit. says program ended and y can do any landing with that

### ISSUE THREAD

**Issue by GAMETROX50** [giuliodondi/kOS-Shuttle-OPS3#10]

**Comment by giuliodondi** [comment]
Use the description box instead of writing a poem in the title. Add details on what situation you were in, you did, what you expected to happen and what you see, with screenshots. 
I'm in no condition to give assistance like this.

**Comment by GAMETROX50** [comment]
ok I did the launch with ops1. and after making the orbit I tried to run the program ops3_deorbit and it said program ended and I can't do anything else except run ops3

**Comment by GAMETROX50** [comment]
I also have this problem
![Screenshot 08-10-2024 18_53_55](https://github.com/user-attachments/assets/6b8e7fbc-5413-4c24-8863-64cbb0b8de65)

**Comment by giuliodondi** [comment]
One problem per issue, please. Otherwise things get mixed up.

Did you actually add a manoeuvre node when you run the deorbit program?
Do you use Principia? If so did you toggle the show nodes on the navball?

**Comment by GAMETROX50** [comment]
I did use principia but I still didn't understand much because when I edited the node it went anywhere, I mean when I edited it the node moved everywhere and I don't understand how to use principia I think that's what I'm missing

**Comment by GAMETROX50** [comment]
It also takes off from the KSC, which is probably interfering with what platform I should use in these cases to have a track record with the Vace Edwards.

**Comment by giuliodondi** [comment]
> It also takes off from the KSC, which is probably interfering with what platform I should use in these cases to have a track record with the Vace Edwards

I really do not understand what this means. In any case where you lift off and where you want to land has no bearing on the issue at hand.

> I did use principia but I still didn't understand much because when I edited the node it went anywhere, I mean when I edited it the node moved everywhere and I don't understand how to use principia I think that's what I'm missing

When you create a manoeuvre node in the Principia planner it only exists for Principia and the rest of the game doesn't know about it. You need to add it to the navball so that it's translated into a KSP node that kOS can pick up. This is where your problem is.

You can find tutorials on how to use Principia elsewhere. For now the problem has been pinpointed and there's no bug in my program so I'll close this issue.
