### ISSUE TITLE
Program lost control while exiting HAC

### ISSUE THREAD

**Issue by atonsis** [giuliodondi/kOS-Shuttle-OPS3#9]
As the title says. Shuttle made the turn around the HAC and was lining up for the runway for the final approach when the program errored out and control was lost. 
![screenshot32](https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/85537834/5242cd54-5e0b-41a9-9187-42885cc6f4f4)
![screenshot33](https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/85537834/e577e06c-6fcc-465e-a35e-74f4c5147b3f)
![screenshot34](https://github.com/giuliodondi/kOS-Shuttle-OPS3/assets/85537834/bb9b119b-2f28-49f5-803a-372e84469a2e)

**Comment by giuliodondi** [comment]
The first screenshot shows that you were already far too slow and below altitude at that point, you should be close to altitude profile and about 160-180 m/s.
The script stalled you out trying to recover the altitude profile (screenshot 2) and then gave up (screenshot 3).

Whatever the issue is, it happened way before the moment you posted these screenshots, you should have never found yourself in this situation.

Another issue is that you were out of RCS fuel, if you had ran out during reentry you would have lost control for sure.

Things you should try:
- make sure you installed the ShuttleSystem mod correctly and that you didn't overwrite the RO configs or something
- go to Ships/Script/Shuttle_OPS3/parameters.ks and set 'full_debug' to TRUE
- after that, do another reentry and you should find two new files: 'Ships/Script/Shuttle_OPS3/LOGS/entry_dump.csv' and 'Ships/Script/Shuttle_OPS3/LOGS/taem_dump.csv', attach those files here so I can have a detailed picture

**Comment by giuliodondi** [comment]
closed due to lack of feedback
